package MediPass;

public enum Droit {
		//Droits de l'administrateur
		CREER_COMPTE_PROFESSIONNEL,
		MODIFIER_COMPTE_PROFESSIONNEL,
		SUSPENDRE_COMPTE_PROFESSIONNEL,
		SUPPRIMER_COMPTE_PROFESSIONNEL,
		
		// DROITS du professionnel de santé
		CREER_COMPTE_PATIENT,
		CREER_DOSSIER_MEDICAL,
		PROGRAMMER_CONSULTATION,
		CONSULTER_DOSSIERMEDICAL,
		AJOUTER_ANTECEDENT,
		MODIFIER_DOSSIER_PATIENT,
		GERER_PLANNING,
		RECHERCHER_PATIENT,
		
		
		// DROITS du patient 
		 CONSULTER_MON_DOSSIER_MEDICAL,
		
	}


	